(function installStructuredEditor(global) {
  const CONTROL_SELECTOR="[data-structured-editor-control]";
  const CAPTURE_SELECTOR=".source-snippet, [data-legacy-note-image]";
  let editorSequence=0;
  function dispatchEditorInput(editor){editor.dispatchEvent(new Event("input",{bubbles:true}));}
  function focusInside(element){const selection=global.getSelection?.();if(!selection)return;const range=document.createRange();range.selectNodeContents(element);range.collapse(true);selection.removeAllRanges();selection.addRange(range);element.focus?.();}
  function createWritingSpace(){const paragraph=document.createElement("p");paragraph.className="personal-note-text";paragraph.dataset.timestamp=String(Date.now());paragraph.append(document.createElement("br"));return paragraph;}
  // Refreshes the timestamp on whichever top-level block the caret is
  // currently in, so editing existing content (not just adding new blocks)
  // is recognized as a real change by the conflict-merge timestamp compare.
  function touchActiveBlockTimestamp(editor){if(!editor)return;const selection=global.getSelection?.();if(!selection||selection.rangeCount===0)return;let node=selection.getRangeAt(0).startContainer;if(node.nodeType===Node.TEXT_NODE)node=node.parentElement;if(!node||node===editor||!editor.contains(node))return;while(node.parentElement&&node.parentElement!==editor)node=node.parentElement;if(node.parentElement===editor)node.dataset.timestamp=String(Date.now());}
  function compactBlankCaptureSeparators(editor){const captures=Array.from(editor.querySelectorAll(CAPTURE_SELECTOR));captures.forEach((capture)=>{const removable=[];let node=capture.nextSibling;while(node){if(node.nodeType===Node.TEXT_NODE){if(node.textContent.trim())return;removable.push(node);node=node.nextSibling;continue;}if(node.nodeType!==Node.ELEMENT_NODE)return;if(node.matches(CAPTURE_SELECTOR)){removable.forEach((item)=>item.remove());return;}const isBlankSeparator=node.matches("br")||(node.matches("p, div")&&!node.textContent.trim()&&!node.querySelector("img, video, audio, table, iframe"));if(!isBlankSeparator)return;removable.push(node);node=node.nextSibling;}});}
  function getContentBlocks(editor,normalizeText=false){if(normalizeText){Array.from(editor.childNodes).forEach((node)=>{if(node.nodeType!==Node.TEXT_NODE||!node.textContent.trim())return;const paragraph=document.createElement("p");paragraph.className="manual-content-block";paragraph.textContent=node.textContent;node.replaceWith(paragraph);});}const captures=Array.from(editor.querySelectorAll(CAPTURE_SELECTOR));const personal=Array.from(editor.querySelectorAll(".personal-note-text, .personal-note-block"));const manual=Array.from(editor.children).filter((element)=>{if(element.matches(CONTROL_SELECTOR)||element.matches(CAPTURE_SELECTOR)||element.matches(".personal-note-text, .personal-note-block, .legacy-image-position, .legacy-image-deleted"))return false;if(element.querySelector?.(CAPTURE_SELECTOR))return false;return element.matches("p, div, blockquote, pre, ul, ol, h1, h2, h3, h4, h5, h6, table");});return Array.from(new Set([...captures,...personal,...manual])).sort((a,b)=>a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1);}
  function clearBlockState(editor){editor.querySelectorAll(CAPTURE_SELECTOR+", .structured-content-block").forEach((block)=>{block.removeAttribute("draggable");block.classList.remove("structured-content-block","structured-draggable","structured-dragging");});}
  function removeGaps(editor){editor.querySelectorAll(CONTROL_SELECTOR).forEach((control)=>control.remove());clearBlockState(editor);editor.classList.remove("structured-editing");}
  function createGap(editor){const gap=document.createElement("button");gap.type="button";gap.className="structured-edit-gap";gap.dataset.structuredEditorControl="";gap.contentEditable="false";gap.setAttribute("aria-label","Add writing space here");gap.title="Add writing space here";gap.addEventListener("click",(event)=>{event.preventDefault();event.stopPropagation();const paragraph=createWritingSpace();gap.before(paragraph);focusInside(paragraph);dispatchEditorInput(editor);});return gap;}
  function moveBlock(editor,block,direction){const blocks=getContentBlocks(editor);const index=blocks.indexOf(block);const target=blocks[index+direction];if(!target)return;if(direction<0)target.before(block);else target.after(block);showGaps(editor);dispatchEditorInput(editor);}
  function addBlockControls(editor,blocks){blocks.forEach((block,index)=>{block.classList.add("structured-content-block");const actions=document.createElement("div");actions.className="structured-block-actions";actions.dataset.structuredEditorControl="";actions.contentEditable="false";const up=document.createElement("button");up.type="button";up.className="structured-move-button";up.textContent="Move Up";up.disabled=index===0;up.addEventListener("click",(event)=>{event.preventDefault();event.stopPropagation();moveBlock(editor,block,-1);});const down=document.createElement("button");down.type="button";down.className="structured-move-button";down.textContent="Move Down";down.disabled=index===blocks.length-1;down.addEventListener("click",(event)=>{event.preventDefault();event.stopPropagation();moveBlock(editor,block,1);});const del=document.createElement("button");del.type="button";del.className="structured-delete-block";del.textContent="Delete content";del.addEventListener("click",(event)=>{event.preventDefault();event.stopPropagation();if(!global.confirm("Delete this entire content block?"))return;if(block.matches("[data-legacy-note-image]")){const marker=document.createElement("span");marker.className="legacy-image-deleted";block.replaceWith(marker);}else block.remove();showGaps(editor);dispatchEditorInput(editor);});actions.append(up,down,del);block.before(actions);});}
  function showGaps(editor){removeGaps(editor);editor.classList.add("structured-editing");const blocks=getContentBlocks(editor,true);if(!blocks.length){editor.append(createGap(editor));return;}blocks.forEach((block)=>{if(!block.previousElementSibling?.matches(".structured-edit-gap"))block.before(createGap(editor));if(!block.nextElementSibling?.matches(".structured-edit-gap"))block.after(createGap(editor));});addBlockControls(editor,blocks);}
  function removeEmptyWritingSpaces(editor){let removed=false;editor.querySelectorAll(".personal-note-text").forEach((paragraph)=>{const hasMedia=paragraph.querySelector("img, video, audio, table");if(!hasMedia&&!paragraph.textContent.trim()){paragraph.remove();removed=true;}});return removed;}
  function enhance(editor,options={}){if(!editor)return;compactBlankCaptureSeparators(editor);const legacyImage=editor.querySelector("[data-legacy-note-image]");const legacyMarker=editor.querySelector(".legacy-image-position");if(legacyImage&&legacyMarker)legacyMarker.replaceWith(legacyImage);editor.querySelectorAll(".legacy-image-position").forEach((marker)=>marker.remove());if(!editor.dataset.structuredEditorId)editor.dataset.structuredEditorId="structured-editor-"+(++editorSequence);removeGaps(editor);editor.parentElement?.querySelectorAll('[data-structured-editor-toolbar="'+editor.dataset.structuredEditorId+'"]').forEach((toolbar)=>toolbar.remove());let editButton=options.toggle||null;if(!editButton){const toolbar=document.createElement("div");toolbar.className="structured-editor-toolbar";toolbar.dataset.structuredEditorToolbar=editor.dataset.structuredEditorId;toolbar.dataset.structuredEditorControl="";editButton=document.createElement("button");editButton.type="button";editButton.className="structured-edit-toggle";toolbar.append(editButton);editor.before(toolbar);}editButton.textContent="Edit";editButton.setAttribute("aria-pressed","false");editButton.onclick=(event)=>{event.preventDefault();const active=editor.classList.contains("structured-editing");if(active){removeGaps(editor);if(removeEmptyWritingSpaces(editor))dispatchEditorInput(editor);editButton.textContent="Edit";editButton.setAttribute("aria-pressed","false");}else{showGaps(editor);editButton.textContent="Done";editButton.setAttribute("aria-pressed","true");}};}
  function serialize(editor){if(!editor)return"";getContentBlocks(editor,true).forEach((block)=>{if(!block.dataset.timestamp)block.dataset.timestamp=String(Date.now());});const clone=editor.cloneNode(true);clone.querySelectorAll(CONTROL_SELECTOR).forEach((control)=>control.remove());clone.querySelectorAll("[data-legacy-note-image]").forEach((image)=>{const marker=document.createElement("span");marker.className="legacy-image-position";image.replaceWith(marker);});clone.querySelectorAll(CAPTURE_SELECTOR+", .structured-content-block").forEach((block)=>{block.removeAttribute("draggable");block.classList.remove("structured-content-block","structured-draggable","structured-dragging");});clone.querySelectorAll(".legacy-image-deleted").forEach((marker)=>marker.remove());clone.classList.remove("structured-editing");clone.removeAttribute("data-structured-editor-id");return clone.innerHTML;}
  function hasDeletedLegacyImage(editor){return Boolean(editor?.querySelector(".legacy-image-deleted"));}
  global.SnipazeStructuredEditor=Object.freeze({enhance,serialize,hasDeletedLegacyImage,touchActiveBlockTimestamp});
})(globalThis);
